traiterJson({
"trait":2,
"scoreJ":25,
"scoreJ5":0,
"scoreR":22,
"scoreR5":0,
"bonusJ":0,
"malusJ":5,
"bonusR":0,
"malusR":4,
"cols":[
	{"nb":2, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2}
]
});